### ISSUE TITLE
Max Volume

### ISSUE THREAD

**Issue by Jaqster** [microsoft/makecode-minecraft-music#13]
This is 100 in Minecraft, but in all our other targets it's 255.
Any thoughts on this?  Should we be consistent?
![image](https://github.com/microsoft/makecode-minecraft-music/assets/22108954/5e78790c-ed46-4155-b393-eefc62a34404)

![image](https://github.com/microsoft/makecode-minecraft-music/assets/22108954/e35f7293-7b13-4269-9533-9d44386eeef8)
![image](https://github.com/microsoft/makecode-minecraft-music/assets/22108954/a6509101-87e5-4521-95ab-f0dba3dfd63e)

**Comment by srietkerk** [comment]
Minecraft volume is different from how volume is handled in our other targets. I'm guessing we're using 255 in micro:bit and arcade due to hardware considerations, but since there isn't any hardware to consider in Minecraft, the max volume value of 100 makes sense. 

Basically, Minecraft volume is on a float spectrum between 0 and 1 and the 0 to 100 value used in the block is essentially a multiplier. So if a user sets the volume to 50, the value that will be used for Minecraft volume will be 0.5. According to the Minecraft wiki about volume, changing the volume value will just modify the distance in which a sound can be heard, so higher values allows the sound to be heard from farther distances and lower values not as far.
